In [54]:
import pandas as pd
import json
import os
import spacy
import numpy as np

In [25]:
nlp = spacy.load('en_core_web_md')

In [5]:
# desc_path = '../../dataset/descriptions/region_descriptions.json'
# desc_json = pd.read_json(desc_path)

In [166]:
image_desc = {}
for image_id in df.ID.values:
    
    desc = df[df.ID==image_id].Desc.values[0]
    desc = desc.replace('..','.')
    image_desc[image_id]=desc

In [169]:
df = pd.DataFrame.from_dict(image_desc,orient='index').reset_index()
df.columns = ["ID","Desc"]
df.head()
df.to_csv('../../dataset/descriptions/region_descriptions_50000.csv',index=False)

In [170]:
df = pd.read_csv('../../dataset/descriptions/region_descriptions_50000.csv')

In [171]:
df[df.ID==2370764].Desc.values[0]

'A clock mounted to a wall. a sign on a wall. a blue support beam. a wooden pillar in a building. bars across a window. a light in a ceiling. a light at the bottom of a pole. a bar at an entrance. writing on a sign. a bright light.'

13837847

KeyboardInterrupt: 

In [35]:
desc_json.id.values.shape

(108077,)

In [21]:
type(images_descs)

str

In [38]:
for image_descs in images_descs:
    print(image_descs['regions'])
    break

262


In [17]:
imgs = os.listdir('../../dataset/train_images/VG_100K/')
len(imgs)

108249

In [18]:
folder_images = []
for im in imgs:
    folder_images.append(int(im.split('.')[0]))

In [ ]:
for v in desc_json.id.values:
    if v not in folder_images:
        print(v)
        break

In [14]:
desc_json.id.values

array([      1,       2,       3, ..., 2417994, 2417995, 2417997])

In [45]:
word_count = {}
for d in df.Desc.values:
    t = nlp(d.lower())
    words = [str(word) for word in t]
#     print(words)
    
    for word in words:
        if word not in word_count.keys():
            word_count[word]=1
        else:
            word_count[word]+=1

df_wcount['words']=word_count.keys()
df_wcount['w_count']=word_count.values()
df_wcount = df_wcount.sort_values(by='w_count',ascending=False).reset_index()
df_wcount['index']+=1
df_wcount.to_csv('../../dataset/descriptions/visual_genome_vocab_count.csv',index=False)

ValueError: Length of values does not match length of index

In [143]:
new_row = {'words':'endseq', 'w_count':50000, 'index':20794}
# df_wcount1 = pd.DataFrame()
# df_wcount1['words']=word_count.keys()
# df_wcount1['w_count']=word_count.values()
# df_wcount1 = df_wcount1.sort_values(by='w_count',ascending=False).reset_index()
# df_wcount1['index']+=1
# df_wcount1.to_csv('../../dataset/descriptions/visual_genome_vocab_count.csv',index=False)

In [144]:
df_wcount = pd.read_csv('../../dataset/descriptions/visual_genome_vocab_count.csv')
display(df_wcount.head())
new_row = pd.Series(data={'words':'endseq', 'w_count':50000, 'index':20794},name='x')
print(df_wcount.shape)
df_wcount = df_wcount.append(new_row,ignore_index=False)
print(df_wcount.shape)
df_wcount.to_csv('../../dataset/descriptions/visual_genome_vocab_count.csv',index=False)

index words  w_count
0   3434     .   450076
1  13908     a   200676
2  14934   the   198458
3  16021    on   122073
4  10923    of    88941

(20793, 3)
(20794, 3)


In [145]:
df_wcount[df_wcount.words=='endseq'].head()

index   words  w_count
x  20794  endseq    50000

In [97]:
new_words= [word for word in df_wcount['words'].values if not word.isalnum()]
print(len(new_words),new_words)

597 ['.', '..', "'s", ' ', ',', '-', '"', "'", '&', '/', 'w/', '[', '\n', '@', "n't", ']', '?', ':', ';', 'p.', 't.v', '...', '  ', '!', '$', '_', 'w.', 'u.s', 'n.', 'a.', "o'clock", 'c.', '#', 'x.', '(', 'r.', ')', 'e.', 's.', 't.', 'b.', '1/2', 'l.', 'man`s', 'woman`s', 'm.', 'c-130', '=', 'black+white', '   ', '....', 'and/or', 'o.', 'red+white', 'dog`s', 'i.', 'girl`s', 'v.', 'm&m', 'g.', '......', 'f.', '+', '.....', 'sr-71', 'y.', "'m", 'co.', 'h.', 'cow`s', 'j.', 'd.', '`', 'boy`s', '%', 'man;s', '--', '\n\n', 't-', '2:35', '1:45', 'u.', 'w/o', 'red+black', 'at&t', '11:50am', '1.00', '12:00', '3:17', '7:05', "'re", 'brown+white', '1/3', 'back+one', 'i.d', '/or', '1:55', 'green+white', '10:50', '12:43', '                                    ', 'b+w', '4-post', 'child`s', '11:20', '3:00', 'trunk+branches', '12:40', 'www.myprofe.com', 'person`s', 'k.', 'catcher`s', '9.99', 'free!.', '    ', 'a&m', '3-way', '3:55', 'sea+sky', '11:05', '4-way', '2:20', 'tool+a', 'house/', 'him!.', '11

In [153]:
w_to_co = df_wcount
w_to_co.index = w_to_co.words
w_to_co = w_to_co['index'].to_dict()
# print(w_to_co)
co_to_w = df_wcount
co_to_w.index = co_to_w['index']
co_to_w = co_to_w['words'].to_dict()
# print(co_to_w)

In [154]:
df_wcount.shape

(20794, 3)

In [100]:
vocab_size =df_wcount.shape[0]
co_to_w[13]

'troaster'

In [146]:
embedding_matrix = pd.read_pickle('../../dataset/descriptions/visual_genome_initial_emb_mat.p')
embedding_matrix = embedding_matrix.values

In [345]:
df_emb = pd.DataFrame(embedding_matrix)
df_emb.to_pickle('../../dataset/descriptions/visual_genome_initial_emb_mat.p')

In [70]:
nlp(co_to_w[vocab_size]).vector

array([ 1.1465e-01,  7.6327e-02, -1.8594e-01,  1.5315e-02, -2.0193e-03,
       -2.7311e-01, -1.6172e-01,  2.8018e-01, -1.3862e-01,  1.9825e+00,
        1.8789e-01, -5.9647e-02, -1.4824e-01,  5.9303e-01,  2.5403e-01,
        1.1026e-01,  2.4206e-01,  1.3235e+00, -2.0395e-01,  2.8434e-01,
       -1.7635e-01,  4.6253e-02,  6.5614e-01,  1.5122e-01,  6.2570e-02,
       -9.5560e-02,  4.7827e-01,  2.8925e-01, -1.7460e-01, -2.3400e-01,
        4.2377e-01,  4.9269e-01,  4.3168e-02, -1.5458e-01,  1.0105e-01,
       -5.3624e-01,  5.9711e-01,  3.3720e-01,  4.4236e-01,  7.1995e-02,
        6.7550e-02, -1.2614e-01, -6.7101e-01,  6.7833e-01, -3.1274e-01,
       -6.6834e-01,  2.0954e-01, -3.1846e-01, -4.4543e-01,  2.5959e-01,
        1.8000e-01, -5.6818e-01, -4.9998e-01,  5.0180e-01, -1.5847e-01,
        4.5843e-01,  1.7503e-01,  4.1826e-01, -2.7257e-01,  2.6886e-01,
       -3.3366e-02, -2.5430e-01,  4.3955e-02, -1.2620e-01,  3.3597e-01,
        1.5442e-02,  2.7599e-01, -7.6766e-01,  2.0519e-01,  7.95

In [147]:
embedding_matrix = np.insert(arr=embedding_matrix,obj=20794,values=(np.random.random((300))-0.5),axis=0)

In [343]:
embedding_matrix=embedding_matrix+1e-6

In [344]:
embedding_matrix[0]

array([1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
       1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06, 1.e-06,
      

In [155]:
nlp(co_to_w[20794]),nlp(co_to_w[20794]).vector

(endseq,
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

In [158]:
embedding_matrix[20792]

array([ 1.14650004e-01,  7.63270035e-02, -1.85939997e-01,  1.53150000e-02,
       -2.01929989e-03, -2.73110002e-01, -1.61719993e-01,  2.80180007e-01,
       -1.38620004e-01,  1.98249996e+00,  1.87889993e-01, -5.96470013e-02,
       -1.48240000e-01,  5.93029976e-01,  2.54029989e-01,  1.10260002e-01,
        2.42060006e-01,  1.32350004e+00, -2.03950003e-01,  2.84339994e-01,
       -1.76349998e-01,  4.62529995e-02,  6.56140029e-01,  1.51219994e-01,
        6.25699982e-02, -9.55599993e-02,  4.78269994e-01,  2.89249986e-01,
       -1.74600005e-01, -2.33999997e-01,  4.23770010e-01,  4.92689997e-01,
        4.31680009e-02, -1.54579997e-01,  1.01049997e-01, -5.36239982e-01,
        5.97109973e-01,  3.37199986e-01,  4.42360014e-01,  7.19949976e-02,
        6.75500035e-02, -1.26139998e-01, -6.71010017e-01,  6.78330004e-01,
       -3.12739998e-01, -6.68340027e-01,  2.09539995e-01, -3.18459988e-01,
       -4.45430011e-01,  2.59590000e-01,  1.80000007e-01, -5.68180025e-01,
       -4.99980003e-01,  

In [159]:
df_emb = pd.DataFrame(embedding_matrix)
df_emb.to_pickle('../../dataset/descriptions/visual_genome_initial_emb_mat.p')

In [173]:
import tensorflow as tf

In [325]:
inp = np.array([
                    [
                        [0,0,0,0,0,0],
                        [0,0,0,0,0,0],
                        [0,0,0,0,0,0],
                        [0,0,0,0,0,0],
                        [0,0,0,0,0,0],
                        [0,0,0,0,0,0],
                        [0,0,0,0,0,0],
                        [3.0,2.0,1.0,2.40,3.50,5.20],
                        [1.0,2.0,3.0,3.40,1.60,5.20],
                        [2.30,1.60,4.10,3.20,0.50,3.90]
                    ]
                ])
inp = inp+0.00001
print(inp)
padding_mask = np.array([[[0],[0],[0],[0],[0],[0],[0],[1],[1],[1]]])
padding_mask.shape

[[[1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05
   1.00000e-05]
  [1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05
   1.00000e-05]
  [1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05
   1.00000e-05]
  [1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05
   1.00000e-05]
  [1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05
   1.00000e-05]
  [1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05
   1.00000e-05]
  [1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05 1.00000e-05
   1.00000e-05]
  [3.00001e+00 2.00001e+00 1.00001e+00 2.40001e+00 3.50001e+00
   5.20001e+00]
  [1.00001e+00 2.00001e+00 3.00001e+00 3.40001e+00 1.60001e+00
   5.20001e+00]
  [2.30001e+00 1.60001e+00 4.10001e+00 3.20001e+00 5.00010e-01
   3.90001e+00]]]


(1, 10, 1)

In [464]:
graph = tf.Graph()
with graph.as_default():
    x = tf.convert_to_tensor(inp,dtype='float',name='x')
    p = tf.convert_to_tensor(padding_mask,dtype='float',name='p')
#     q = tf.keras.layers.Conv1D(kernel_size=1,strides=1,activation='relu',filters=8,padding='same',kernel_initializer='glorot_uniform')(x)
#     k = tf.keras.layers.Conv1D(kernel_size=1,strides=1,activation='relu',filters=8,padding='same',kernel_initializer='glorot_uniform')(x)
#     v = tf.keras.layers.Conv1D(kernel_size=1,strides=1,activation='relu',filters=8,padding='same',kernel_initializer='glorot_uniform')(x)
#     s = tf.keras.backend.batch_dot(q, tf.keras.backend.permute_dimensions(k,(0,2,1)))
    
    
    
#     beta = tf.keras.backend.softmax(s, axis=-1)
#     beta = tf.keras.layers.Multiply()([beta,padding_mask])
#     o = tf.keras.backend.batch_dot(beta,v)
#     o = tf.keras.layers.BatchNormalization()(o)


#     n = Dense(10,activation='relu')(x)
#     print(n)
    g1 = tf.keras.layers.Dense(1)
    x_exp = tf.keras.backend.expand_dims(axis=-1,x=x)
    g1_out = g1(x_exp)
    
    g1_out_relu = tf.keras.backend.squeeze(axis=-1,x=tf.keras.layers.Activation('relu')(g1_out))
    g1_out_elu = tf.keras.backend.squeeze(axis=-1,x=tf.keras.layers.Activation('elu')(g1_out))
    g1_out_linear = tf.keras.backend.squeeze(axis=-1,x=tf.keras.layers.Activation('linear')(g1_out))
#     g1_weights = tf.convert_to_tensor(g1.get_weights())
#     g1_out = tf.keras.backend.squeeze(axis=-1,x=g1_out)
#     print(g1_out)
    initialize = tf.global_variables_initializer()
    
x


<tf.Tensor 'x:0' shape=(1, 10, 6) dtype=float32>

In [469]:

with tf.Session(graph=graph) as sess:
    sess.run(initialize)
    display(pd.DataFrame(sess.run(x)[0]))
    display(pd.DataFrame(sess.run(g1_out_relu)[0]))
    display(pd.DataFrame(sess.run(g1_out_elu)[0]))
    display(pd.DataFrame(sess.run(g1_out_linear)[0]))
#     display(pd.DataFrame(sess.run(o)[0]))
# sess.run(feed_dict={x.name:inp.tolist()},fetches=q)
# q.eval(session=tf.Session(),feed_dict={'x':inp.tolist()})

0        1        2        3        4        5
0  0.00001  0.00001  0.00001  0.00001  0.00001  0.00001
1  0.00001  0.00001  0.00001  0.00001  0.00001  0.00001
2  0.00001  0.00001  0.00001  0.00001  0.00001  0.00001
3  0.00001  0.00001  0.00001  0.00001  0.00001  0.00001
4  0.00001  0.00001  0.00001  0.00001  0.00001  0.00001
5  0.00001  0.00001  0.00001  0.00001  0.00001  0.00001
6  0.00001  0.00001  0.00001  0.00001  0.00001  0.00001
7  3.00001  2.00001  1.00001  2.40001  3.50001  5.20001
8  1.00001  2.00001  3.00001  3.40001  1.60001  5.20001
9  2.30001  1.60001  4.10001  3.20001  0.50001  3.90001

0         1         2         3         4         5
0  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
1  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
2  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
3  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
4  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
5  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
6  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
7  0.362929  0.241953  0.120977  0.290343  0.423417  0.629076
8  0.120977  0.241953  0.362929  0.411319  0.193563  0.629076
9  0.278246  0.193563  0.496002  0.387124  0.060489  0.471807

0         1         2         3         4         5
0  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
1  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
2  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
3  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
4  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
5  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
6  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
7  0.362929  0.241953  0.120977  0.290343  0.423417  0.629076
8  0.120977  0.241953  0.362929  0.411319  0.193563  0.629076
9  0.278246  0.193563  0.496002  0.387124  0.060489  0.471807

0         1         2         3         4         5
0  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
1  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
2  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
3  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
4  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
5  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
6  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001
7  0.362929  0.241953  0.120977  0.290343  0.423417  0.629076
8  0.120977  0.241953  0.362929  0.411319  0.193563  0.629076
9  0.278246  0.193563  0.496002  0.387124  0.060489  0.471807

In [397]:
3.0*0.29

0.8699999999999999

In [201]:
s = tf.keras.backend.softmax(g,axis=-1)
pd.DataFrame(s.eval(session=tf.Session()))

0             1             2             3             4  \
0  2.843231e-20  4.219729e-18  6.262634e-16  9.294572e-14  1.379437e-11   
1  3.523872e-24  1.421631e-21  5.735271e-19  2.313773e-16  9.334428e-14   
2  4.355635e-28  4.776534e-25  5.238105e-22  5.744280e-19  6.299368e-16   
3  5.378381e-32  1.603273e-28  4.779289e-25  1.424686e-21  4.246929e-18   
4  6.638858e-36  5.379522e-32  4.359072e-28  3.532193e-24  2.862165e-20   

              5             6             7         8         9  
0  2.047266e-09  3.038412e-07  4.509403e-05  0.006693  0.993262  
1  3.765777e-11  1.519223e-08  6.128982e-06  0.002473  0.997521  
2  6.908096e-13  7.575646e-10  8.307705e-07  0.000911  0.999088  
3  1.265992e-14  3.773868e-11  1.124974e-07  0.000335  0.999665  
4  2.319237e-16  1.879297e-12  1.522810e-08  0.000123  0.999877

In [207]:
np.exp(g[0][-1])/np.sum(np.exp(g[0]))

0.99326205

In [205]:
np.sum(np.exp(g[0]))

3.5171253e+19

In [342]:
nlp('.').vector

array([ 0.012001 ,  0.20751  , -0.12578  , -0.59325  ,  0.12525  ,
        0.15975  ,  0.13748  , -0.33157  , -0.13694  ,  1.7893   ,
       -0.47094  ,  0.70434  ,  0.26673  , -0.089961 , -0.18168  ,
        0.067226 ,  0.053347 ,  1.5595   , -0.2541   ,  0.038413 ,
       -0.01409  ,  0.056774 ,  0.023434 ,  0.024042 ,  0.31703  ,
        0.19025  , -0.37505  ,  0.035603 ,  0.1181   ,  0.012032 ,
       -0.037566 , -0.5046   , -0.049261 ,  0.092351 ,  0.11031  ,
       -0.073062 ,  0.33994  ,  0.28239  ,  0.13413  ,  0.070128 ,
       -0.022099 , -0.28103  ,  0.49607  , -0.48693  , -0.090964 ,
       -0.1538   , -0.38011  , -0.014228 , -0.19392  , -0.11068  ,
       -0.014088 , -0.17906  ,  0.24509  , -0.16878  , -0.15351  ,
       -0.13808  ,  0.02151  ,  0.13699  ,  0.0068061, -0.14915  ,
       -0.38169  ,  0.12727  ,  0.44007  ,  0.32678  , -0.46117  ,
        0.068687 ,  0.34747  ,  0.18827  , -0.31837  ,  0.4447   ,
       -0.2095   , -0.26987  ,  0.48945  ,  0.15388  ,  0.0529